use 5.008008;
use ExtUtils::MakeMaker;
# See lib/ExtUtils/MakeMaker.pm for details of how to influence
# the contents of the Makefile that is written.
WriteMakefile(
    NAME              => 'Google::Adwords',
    VERSION_FROM      => 'lib/Google/Adwords.pm', # finds $VERSION
    PREREQ_PM         => {
        'SOAP::Lite'    => 0,
        'version'       => 0,
        'Readonly'      => 0,
        'Class::Accessor::Chained'  => 0,
        'Date::Manip'   => 0,
        'Test::Class'   => 0,
        'Test::More'    => 0,
        'IO::Prompt'    => 0,
    }, # e.g., Module::Name => 1.1
    ($] >= 5.005 ?     ## Add these new keywords supported since 5.005
      (ABSTRACT_FROM  => 'lib/Google/Adwords.pm', # retrieve abstract from module
       AUTHOR         => 'Rohan Almeida <rohan.almeida@gmail.com>') : ()),
);
