--- #YAML:1.0
name:                Google-Adwords
version:             v1.9.3
abstract:            an interface which abstracts the Google Adwords SOAP API
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Class::Accessor:               0
    Class::Accessor::Chained:      0
    Crypt::SSLeay:                 0
    Date::Manip:                   0
    HTML::Entities:                0
    Readonly:                      0
    SOAP::Lite:                    0.66
    Test::Class:                   0
    Test::MockModule:              0
    Test::More:                    0
    version:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Rohan Almeida <rohan@almeida.in>
