# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Google-Adwords
version:      v0.5.0
version_from: lib/Google/Adwords.pm
installdirs:  site
requires:
    Class::Accessor::Chained:      0.01
    Date::Manip:                   5.42
    IO::Prompt:                    0.099004
    Readonly:                      1.03
    SOAP::Lite:                    0.65
    Test::Class:                   0.11
    Test::More:                    0.62
    version:                       0.50

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
