# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Google-Adwords
version:      v0.0.1
version_from: lib/Google/Adwords.pm
installdirs:  site
requires:
    Class::Accessor::Chained:      0
    Date::Manip:                   0
    IO::Prompt:                    0
    Readonly:                      0
    SOAP::Lite:                    0
    Test::Class:                   0
    Test::More:                    0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
